Initial import
tutu-ru/php-etcd pull request #1
Opened 2018-11-26 10:29 UTC by todoshcenko

2018-11-29 06:20 UTC, alexkrass commented on tests/EtcdClientFactoryTest.php
> +        putenv(EtcdClientFactory::ENV_VAR_PORT . '=24001');
для этих тестов надо еще что то настраивать ?

2018-11-29 07:12 UTC, todoshcenko commented on tests/EtcdClientFactoryTest.php
> +        putenv(EtcdClientFactory::ENV_VAR_PORT . '=24001');
Именно для этого теста ничего не надо, тут специально указываются некорректные данные.
Но для общего прогона etcd нужен, в README написано об этом (и как его запустить через docker).

2018-11-29 08:16 UTC, alexkrass requested changes

2018-11-29 08:16 UTC, alexkrass commented on src/EtcdClient.php
> +    public const PATH_SEPARATOR = '/';
константа только в этом классе используется ?
может private

такой же вопрос про видимость других констант тут ?

2018-11-29 14:27 UTC, alexkrass commented on src/EtcdClient.php
> +        $path = trim($path, self::PATH_SEPARATOR) . self::PATH_SEPARATOR;
только PATH_SEPARATOR режем ?
пробелы и прочее нет ?

2018-11-30 10:05 UTC, todoshcenko commented on src/EtcdClient.php
> +        $path = trim($path, self::PATH_SEPARATOR) . self::PATH_SEPARATOR;
Все так. Здесь происходит нормализация разделителей

2018-11-30 10:06 UTC, todoshcenko commented on src/EtcdClient.php
> +    public const PATH_SEPARATOR = '/';
`PATH_SEPARATOR` — публичная.

остальные сделал приватными, так как сейчас мы не даем использовать флаги. при запросах.

2018-12-04 11:16 UTC, alexkrass approved these changes

2018-12-06 16:15 UTC, merged